// <auto-generated />
using System;
using Client.Management.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Client.Management.API.Migrations
{
    [DbContext(typeof(ClientDataContext))]
    [Migration("20250311025831_Data Seeding")]
    partial class DataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Client.Management.API.Models.Client", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ID = new Guid("102271b1-17d5-49f4-b130-3947a0d1362e"),
                            Address = "123 Main St, Anytown, OR",
                            Email = "doe@hotmail.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Phone = "1234567890"
                        },
                        new
                        {
                            ID = new Guid("76ee3690-1855-40ff-a5a0-42960f6b55d7"),
                            Address = "606 Willow Blvd, There",
                            Email = "brian.rodriguez@example.com",
                            FirstName = "Brian",
                            LastName = "Rodriguez",
                            Phone = "9098087070"
                        },
                        new
                        {
                            ID = new Guid("72820816-59b9-4da9-a255-7e2dbfc07486"),
                            Address = "707 Spruce Grv, Up",
                            Email = "ashley.martinez@hotmail.com",
                            FirstName = "Ashley",
                            LastName = "Martinez",
                            Phone = "3034045050"
                        },
                        new
                        {
                            ID = new Guid("e076e2d0-7803-4dd8-9230-3174e333d670"),
                            Address = "505 Redwood Way, Here",
                            Email = "jessica.garcia@hotmail.com",
                            FirstName = "Jessica",
                            LastName = "Garcia",
                            Phone = "6067078080"
                        },
                        new
                        {
                            ID = new Guid("da1361ad-d2a1-462f-baaf-2251d7dabe5d"),
                            Address = "303 Birch Ct, Somewhere",
                            Email = "emily.davis@hotmail.com",
                            FirstName = "Emily",
                            LastName = "Davis",
                            Phone = "7778889999"
                        },
                        new
                        {
                            ID = new Guid("6182c353-919d-45ce-8c02-3574cad9c79e"),
                            Address = "789 Pine Ln, Othertown",
                            Email = "david.lee@hotmail.com",
                            FirstName = "David",
                            LastName = "Lee",
                            Phone = "5551234567"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
